# Generated by tools/generate_models.py
from __future__ import annotations
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, DateTime, Integer, String, Text, PrimaryKeyConstraint
from datetime import datetime
from zoneinfo import ZoneInfo
# models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
import uuid
import json
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# --- Tabelle di associazione ---

roles_permission = db.Table(
    'roles_permission',
    db.Column('role_id', db.Integer, db.ForeignKey(
        'roles.id', ondelete='CASCADE'), primary_key=True),
    db.Column('permission_id', db.Integer, db.ForeignKey(
        'permissions.id', ondelete='CASCADE'), primary_key=True),
)

user_famiglia = db.Table(
    'user_famiglia',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('famiglia_id', db.Integer, db.ForeignKey(
        'famiglia.id', ondelete='CASCADE'), primary_key=True),
)

user_lavorazioni = db.Table(
    'user_lavorazioni',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('lavorazioni_id', db.Integer, db.ForeignKey(
        'lavorazioni.id', ondelete='CASCADE'), primary_key=True),
)

user_macrofamiglia = db.Table(
    'user_macrofamiglia',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('macrofamiglia_id', db.Integer, db.ForeignKey(
        'macrofamiglia.id', ondelete='CASCADE'), primary_key=True),
)

user_magazzini = db.Table(
    'user_magazzini',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('magazzini_id', db.Integer, db.ForeignKey(
        'magazzini.id', ondelete='CASCADE'), primary_key=True),
)

user_reparti = db.Table(
    'user_reparti',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('reparto_id', db.Integer, db.ForeignKey(
        'reparti.id', ondelete='CASCADE'), primary_key=True),
)

user_risorse = db.Table(
    'user_risorse',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('risorse_id', db.Integer, db.ForeignKey(
        'risorse.id', ondelete='CASCADE'), primary_key=True),
)

user_roles = db.Table(
    'user_roles',
    db.Column('user_id', db.Integer, db.ForeignKey(
        'users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('role_id', db.Integer, db.ForeignKey(
        'roles.id', ondelete='CASCADE'), primary_key=True),
)

# --- Modelli ---


class Causaliattivita(db.Model):
    __tablename__ = 'causaliattivita'

    id = db.Column(db.Integer, primary_key=True)
    DesCausaleAttivita = db.Column(db.Text, nullable=False)
    TipoCausale = db.Column(db.Text, nullable=False)
    CausaleAttivita = db.Column(db.Text, nullable=False)
    CodCategoriaAttivita = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Causaliattivita {self.__dict__}>"


class ChangeEvent(db.Model):
    __tablename__ = 'change_event'

    id = db.Column(db.Integer, primary_key=True)
    topic = db.Column(db.Text, nullable=False)
    scope = db.Column(db.Text)
    payload_json = db.Column(db.Text)
    created_at = db.Column(db.Text, nullable=False,
                           default=lambda: datetime.now(ZoneInfo("Europe/Rome")))

    def __repr__(self):
        return f"<ChangeEvent {self.__dict__}>"


class Famiglia(db.Model):
    __tablename__ = 'famiglia'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Famiglia {self.__dict__}>"


class GiacenzaMateriale(db.Model):
    __tablename__ = 'giacenza_materiale'

    CodArt = db.Column(db.Text)
    CodMag = db.Column(db.Text)
    Giacenza = db.Column(db.Text, nullable=False)
    RifLottoAlfa = db.Column(db.Text, nullable=False)
    DesArt = db.Column(db.Text, nullable=False)

    __table_args__ = (
        db.PrimaryKeyConstraint('CodArt', 'CodMag'),
    )

    def __repr__(self):
        return f"<GiacenzaMateriale {self.__dict__}>"


class InputOdp(db.Model):
    __tablename__ = 'input_odp'

    IdDocumento = db.Column(db.Text)
    IdRiga = db.Column(db.Text)
    RifRegistraz = db.Column(db.Text)
    CodArt = db.Column(db.Text)
    Quantita = db.Column(db.Text)
    NumFase = db.Column(db.Text)
    CodLavorazione = db.Column(db.Text)
    CodRisorsaProd = db.Column(db.Text)
    DataInizioSched = db.Column(db.Text)
    DataFineSched = db.Column(db.Text)
    GestioneLotto = db.Column(db.Text)
    GestioneMatricola = db.Column(db.Text)
    DistintaMateriale = db.Column(db.Text)
    CodMatricola = db.Column(db.Text)
    StatoRiga = db.Column(db.Text)
    CodFamiglia = db.Column(db.Text)
    CodMacrofamiglia = db.Column(db.Text)
    CodMagPrincipale = db.Column(db.Text)
    CodReparto = db.Column(db.Text)
    TempoPrevistoLavoraz = db.Column(db.Text)
    StatoOrdine = db.Column(db.Text)
    CodClassifTecnica = db.Column(db.Text)
    CodTipoDoc = db.Column(db.Text)

    __table_args__ = (
        db.PrimaryKeyConstraint('IdDocumento', 'IdRiga'),
    )

    def __repr__(self):
        return f"<{self.__dict__}>"


class Lavorazioni(db.Model):
    __tablename__ = 'lavorazioni'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Lavorazioni {self.__dict__}>"


class Macrofamiglia(db.Model):
    __tablename__ = 'macrofamiglia'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Macrofamiglia {self.__dict__}>"


class Magazzini(db.Model):
    __tablename__ = 'magazzini'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Magazzini {self.__dict__}>"


class Permissions(db.Model):
    __tablename__ = 'permissions'

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text)

    def __repr__(self):
        return f"<Permissions {self.__dict__}>"


class Reparti(db.Model):
    __tablename__ = 'reparti'

    id = db.Column(db.Integer, primary_key=True)
    codice = db.Column(db.Text, nullable=False)
    descrizione = db.Column(db.Text)

    users = db.relationship(
        "User",
        secondary=user_reparti,
        back_populates="reparti",
    )

    def __repr__(self):
        return f"<Reparti {self.__dict__}>"


class Risorse(db.Model):
    __tablename__ = 'risorse'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Risorse {self.__dict__}>"


class Roles(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text)
    permissions = db.relationship(
        "Permissions",
        secondary=roles_permission,
        backref=db.backref("roles", lazy="dynamic"),
        lazy="dynamic",
    )

    def add_permission(self, permission: "Permissions"):
        if not self.permissions.filter_by(id=permission.id).first():
            self.permissions.append(permission)

    def remove_permission(self, permission: "Permissions"):
        if self.permissions.filter_by(id=permission.id).first():
            self.permissions.remove(permission)

    def has_permission(self, code: str) -> bool:
        return self.permissions.filter_by(code=code).first() is not None

    def __repr__(self):
        return f"<Roles {self.__dict__}>"


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(
        db.String,
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
    )
    username = db.Column(db.String, unique=True, nullable=False)
    active = db.Column(db.Boolean, nullable=False,
                       default=True, server_default=db.text('1'))
    preference = db.Column(db.Text)
    genere = db.Column(db.Text)
    RepartoPrinc = db.Column(db.Text)

    roles = db.relationship(
        "Roles",
        secondary=user_roles,
        backref=db.backref("users", lazy="dynamic"),
        lazy="joined",
    )

    reparti = db.relationship(
        "Reparti",
        secondary=user_reparti,
        back_populates="users",
        lazy="joined",
    )
    # --- helper per preferences (JSON) ---

    @property
    def preferences(self) -> dict:
        if not self.preference:
            return {}
        try:
            return json.loads(self.preference)
        except json.JSONDecodeError:
            return {}

    @property
    def reparto_label(self) -> str:
        """Restituisce il nome del reparto principale da mostrare in UI."""
        if self.reparti:
            return self.reparti.descrizione
        return "N/A"

    @preferences.setter
    def preferences(self, value: dict):
        self.preference = json.dumps(value or {})

    def get_pref(self, key, default=None):
        return self.preferences.get(key, default)

    def set_pref(self, key, value):
        prefs = self.preferences
        prefs[key] = value
        self.preferences = prefs

    # --- helper RBAC ---

    def has_role(self, role_name: str) -> bool:
        return any(r.name == role_name for r in self.roles)

    def has_permission(self, code: str) -> bool:
        return any(r.has_permission(code) for r in self.roles)

    def has_reparto(self, reparto_name: str) -> bool:
        return any(r.codice == reparto_name for r in self.reparti)

    def allowed_reparti_codici(self) -> list[str]:
        return [r.descrizione for r in self.reparti]

    def __repr__(self):
        return f"<Users {self.__dict__}>"


class StatoOdp(db.Model):
    __tablename__ = 'stato_odp'

    id = db.Column(db.Integer, primary_key=True)
    IdDocumento = db.Column(db.Text)
    IdRiga = db.Column(db.Text)
    stato = db.Column(db.Text, server_default=db.text("Pianificato"))
    fase = db.Column(db.Text, server_default=db.text("1"))

    def __repr__(self):
        return f"<StatoOdp {self.__dict__}>"


class TipologieStato(db.Model):
    __tablename__ = 'tipologie_stato'

    id = db.Column(db.Integer, primary_key=True)
    tipo = db.Column(db.Integer)

    def __repr__(self):
        return f"<TipologieStato {self.__dict__}>"
