# Generated by tools/generate_models.py
from __future__ import annotations

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# --- Tabelle di associazione ---

roles_permission = db.Table(
    'roles_permission',
    db.Column('role_id', db.Integer, db.ForeignKey('roles.id', ondelete='CASCADE'), primary_key=True),
    db.Column('permission_id', db.Integer, db.ForeignKey('permissions.id', ondelete='CASCADE'), primary_key=True),
)

user_famiglia = db.Table(
    'user_famiglia',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('famiglia_id', db.Integer, db.ForeignKey('famiglia.id', ondelete='CASCADE'), primary_key=True),
)

user_lavorazioni = db.Table(
    'user_lavorazioni',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('lavorazioni_id', db.Integer, db.ForeignKey('lavorazioni.id', ondelete='CASCADE'), primary_key=True),
)

user_macrofamiglia = db.Table(
    'user_macrofamiglia',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('macrofamiglia_id', db.Integer, db.ForeignKey('macrofamiglia.id', ondelete='CASCADE'), primary_key=True),
)

user_magazzini = db.Table(
    'user_magazzini',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('magazzini_id', db.Integer, db.ForeignKey('magazzini.id', ondelete='CASCADE'), primary_key=True),
)

user_reparti = db.Table(
    'user_reparti',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('reparto_id', db.Integer, db.ForeignKey('reparti.id', ondelete='CASCADE'), primary_key=True),
)

user_risorse = db.Table(
    'user_risorse',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('risorse_id', db.Integer, db.ForeignKey('risorse.id', ondelete='CASCADE'), primary_key=True),
)

user_roles = db.Table(
    'user_roles',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
    db.Column('role_id', db.Integer, db.ForeignKey('roles.id', ondelete='CASCADE'), primary_key=True),
)

# --- Modelli ---

class Causaliattivita(db.Model):
    __tablename__ = 'causaliattivita'

    id = db.Column(db.Integer, primary_key=True)
    DesCausaleAttivita = db.Column(db.Text, nullable=False)
    TipoCausale = db.Column(db.Text, nullable=False)
    CausaleAttivita = db.Column(db.Text, nullable=False)
    CodCategoriaAttivita = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Causaliattivita {self.__dict__}>"

class ChangeEvent(db.Model):
    __tablename__ = 'change_event'

    id = db.Column(db.Integer, primary_key=True)
    topic = db.Column(db.Text, nullable=False)
    scope = db.Column(db.Text)
    payload_json = db.Column(db.Text)
    created_at = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<ChangeEvent {self.__dict__}>"

class Famiglia(db.Model):
    __tablename__ = 'famiglia'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Famiglia {self.__dict__}>"

class GiacenzaMateriale(db.Model):
    __tablename__ = 'giacenza_materiale'

    CodArt = db.Column(db.Text)
    CodMag = db.Column(db.Text)
    Giacenza = db.Column(db.Text, nullable=False)
    RifLottoAlfa = db.Column(db.Text, nullable=False)
    DesArt = db.Column(db.Text, nullable=False)

    __table_args__ = (
        db.PrimaryKeyConstraint('CodArt', 'CodMag'),
    )

    def __repr__(self):
        return f"<GiacenzaMateriale {self.__dict__}>"

class InputOdp(db.Model):
    __tablename__ = 'input_odp'

    IdDocumento = db.Column(db.Text)
    IdRiga = db.Column(db.Text)
    RifRegistraz = db.Column(db.Text)
    CodArt = db.Column(db.Text)
    Quantita = db.Column(db.Text)
    NumFase = db.Column(db.Text)
    CodLavorazione = db.Column(db.Text)
    CodRisorsaProd = db.Column(db.Text)
    DataInizioSched = db.Column(db.Text)
    DataFineSched = db.Column(db.Text)
    GestioneLotto = db.Column(db.Text)
    GestioneMatricola = db.Column(db.Text)
    DistintaMateriale = db.Column(db.Text)
    CodMatricola = db.Column(db.Text)
    StatoRiga = db.Column(db.Text)
    CodFamiglia = db.Column(db.Text)
    CodMacrofamiglia = db.Column(db.Text)
    CodMagPrincipale = db.Column(db.Text)
    CodReparto = db.Column(db.Text)
    TempoPrevistoLavoraz = db.Column(db.Text)
    StatoOrdine = db.Column(db.Text)
    CodClassifTecnica = db.Column(db.Text)
    CodTipoDoc = db.Column(db.Text)

    __table_args__ = (
        db.PrimaryKeyConstraint('IdDocumento', 'IdRiga'),
    )

    def __repr__(self):
        return f"<InputOdp {self.__dict__}>"

class Lavorazioni(db.Model):
    __tablename__ = 'lavorazioni'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Lavorazioni {self.__dict__}>"

class Macrofamiglia(db.Model):
    __tablename__ = 'macrofamiglia'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Macrofamiglia {self.__dict__}>"

class Magazzini(db.Model):
    __tablename__ = 'magazzini'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Magazzini {self.__dict__}>"

class Permissions(db.Model):
    __tablename__ = 'permissions'

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text)

    def __repr__(self):
        return f"<Permissions {self.__dict__}>"

class Reparti(db.Model):
    __tablename__ = 'reparti'

    id = db.Column(db.Integer, primary_key=True)
    codice = db.Column(db.Text, nullable=False)
    descrizione = db.Column(db.Text)

    def __repr__(self):
        return f"<Reparti {self.__dict__}>"

class Risorse(db.Model):
    __tablename__ = 'risorse'

    id = db.Column(db.Integer, primary_key=True)
    Codice = db.Column(db.Text, nullable=False)
    Descrizione = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f"<Risorse {self.__dict__}>"

class Roles(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text)

    def __repr__(self):
        return f"<Roles {self.__dict__}>"

class StatoOdp(db.Model):
    __tablename__ = 'stato_odp'

    id = db.Column(db.Integer, primary_key=True)
    IdDocumento = db.Column(db.Text)
    IdRiga = db.Column(db.Text)
    stato = db.Column(db.Text, server_default=db.text("'Pianificato'"))
    fase = db.Column(db.Text)

    def __repr__(self):
        return f"<StatoOdp {self.__dict__}>"

class TipologieStato(db.Model):
    __tablename__ = 'tipologie_stato'

    id = db.Column(db.Integer, primary_key=True)
    tipo = db.Column(db.Integer)

    def __repr__(self):
        return f"<TipologieStato {self.__dict__}>"

class Users(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.Text, nullable=False)
    username = db.Column(db.Text, nullable=False)
    active = db.Column(db.Integer, nullable=False, server_default=db.text('1'))
    preference = db.Column(db.Text)
    genere = db.Column(db.Text)
    RepartoPrinc = db.Column(db.Text)

    def __repr__(self):
        return f"<Users {self.__dict__}>"
