[Elementi_selezionati]
StatoOrdine = "Pianificata"
[Elementi_esclusi]
CodRisorsaProd = ["01", "02", "03"]
CodMag = ["2", "4", "5", "8", "9", "12", "13"]
CodReparto = ["50", "60"] #da inserire anche il 40?
CodLavorazione = [
    "COS",
    "DEN",
    "ELE",
    "INC",
    "LOG",
    "OSS",
    "PAL",
    "PVD",
    "TAG",
    "VER",
]
CodFamiglia = [
    "PNT",
    "BRA",
    "BRI",
    "BRR",
    "LAV",
    "RIC",
    "ATT",
    "BEV",
    "CAF",
    "ESI",
    "KIT",
    "MER",
    "SCOMM",
    "SSV",
] #da controllare realmente quali mantenere
CodMacrofamiglia = ["BBLAB", "BRR", "ESS"]
CodArt = [
    "RDMU18",
    "RDMU19",
    "RDMU20",
] #lasciare la voce vuota per rimuovere i valori vuoti
[Percorsi]
percorso_db = "//Serverspring02/PythonDB/Avanzamenti_produzione/app/instance/RBAC.db"
[sync_config]
tempo_polling = 2
counter_righe = 0
giorni_settimanali = [0, 1, 2, 3, 4, 5]
ora_inizio = 7
ora_fine = 18
time_zone = "Europe/Rome"
sql_params = "DRIVER={ODBC Driver 18 for SQL Server};SERVER=SERVERSPRING02;DATABASE=BernardiProd;UID=Produzione;PWD=Produzione2025.;Encrypt=no;TrustServerCertificate=no;Pooling=no;MultipleActiveResultSets=False;"
